### ISSUE TITLE
add the option for different electron styles

### ISSUE THREAD

**Issue by jiyometrik** [cgnieder/bohr#2]
I'm using the bohr package to create dot-and-cross diagrams for ionic and covalent bonds, but there doesn't seem to be an option to change/tweak the shape of the individual electrons (see two pictures below - created vs intended). 

Is there something that can do this, and if not, would it be possible to add this feature?

*created*
![image](https://user-images.githubusercontent.com/79387351/152079002-c18c3225-7a59-4c43-8b8b-01d975a11dbd.png)

*intended*
![image](https://user-images.githubusercontent.com/79387351/152079103-2fecc5b0-6bc1-4ce6-8415-202fe6a84d5b.png)

**Comment by cgnieder** [comment]
There are lots of possibilities for customization:

```latex
\documentclass{article}
\usepackage{bohr}

\setbohr{
  nucleus-options-set = { draw = none } ,
  shell-options-set = black ,
  electron-options-set = { black, shade, shading=ball, ball color=red } ,
  electron-radius = 3pt ,
  shell-dist = 15pt ,
  atom-style = \sffamily\bfseries
}

\begin{document}

\bohr{6}{C}

\end{document}
```

![grafik](https://user-images.githubusercontent.com/2248538/152215074-368527d0-86b0-4390-8a6f-5fb421eb2891.png)
